/*
 * NLP API
 * API for calling various NLP methods
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AutoNerResultDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutonlpApi
 */
@Ignore
public class AutonlpApiTest {

    private final AutonlpApi api = new AutonlpApi();

    /**
     * Convenience endpoint that delegates work to either estnlp or genericnlp tools based on input language.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void autoNerTest() throws ApiException {
        List<String> body = null;
        AutoNerResultDto response = api.autoNer(body);

        // TODO: test validations
    }
}
