/*
 * NLP API
 * API for calling various NLP methods
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

import io.swagger.client.ApiException;
import io.swagger.client.model.EstNerResultDto;

/**
 * API tests for EstnlpApi
 */
@Ignore
public class EstnlpApiTest {

    private final EstnlpApi api = new EstnlpApi();

    /**
     * Helps with named entity recognition using estnltk. Extended to also include temporal info.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void estNerTest() throws ApiException {
        List<String> body = null;
        EstNerResultDto response = api.estNer(body);

        // TODO: test validations
    }
}
