/*
 * NLP API
 * API for calling various NLP methods
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.GenericNerResultDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GenericnlpApi
 */
@Ignore
public class GenericnlpApiTest {

    private final GenericnlpApi api = new GenericnlpApi();

    /**
     * Helps with named entity recognition using spaCy. Additionaly uses TextBlob to detect input text&#x27;s language and translate it to English if necessary (as spaCy works best in English).
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genericNerTest() throws ApiException {
        List<String> body = null;
        GenericNerResultDto response = api.genericNer(body);

        // TODO: test validations
    }
}
